SIZE_WINDOW = (1280,720)
SIZE_HERO = (64,64)
SPEED_BULLET = 20
SIZE_BLOCK = (32,32)
SIZE_BULLET = (16,16)
SPEED_HERO = 5

PATH_IMAGE = 'source/image/' 
BLOCK_IMAGE = None#PATH_IMAGE+'block.png'
BULLET_IMAGE = None#PATH_IMAGE+'bullet.png'
HERO_IMAGE = None #PATH_IMAGE + 'playerOgyrcoro.png'